[Ide] Workspace files cache doesn't work on Windows
Solution configuration mappings, in the case of multiple platform targets
being applicable, will use a selector like 'Debug|x86' and 'Debug|Any CPU'.

On Windows, `|` is an invalid character. Thus, sanitize that when choosing
the filename.

```
ERROR [2019-04-25 20:48:05Z]: Error while reloading solution.
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at MonoDevelop.Core.FilePath.Combine(String path) in E:\therzok\monodevelop\main\src\core\MonoDevelop.Core\MonoDevelop.Core\FilePath.cs:line 238
   at MonoDevelop.Ide.TypeSystem.WorkspaceFilesCache.GetProjectCacheFile(Project proj, String configuration) in E:\therzok\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.TypeSystem\WorkspaceFilesCache.cs:line 106
   at MonoDevelop.Ide.TypeSystem.WorkspaceFilesCache.LoadCache(Solution sol) in E:\therzok\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.TypeSystem\WorkspaceFilesCache.cs:line 81
   at MonoDevelop.Ide.TypeSystem.WorkspaceFilesCache.Load(Solution solution) in E:\therzok\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.TypeSystem\WorkspaceFilesCache.cs:line 66
   at MonoDevelop.Ide.TypeSystem.MonoDevelopWorkspace.ProjectSystemHandler.ReloadProjectCache() in E:\therzok\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.TypeSystem\MonoDevelopWorkspace.ProjectSystemHandler.cs:line 550
   at MonoDevelop.Ide.TypeSystem.MonoDevelopWorkspace.<>c__DisplayClass61_0.<<HandleActiveConfigurationChanged>b__0>d.MoveNext() in E:\therzok\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.TypeSystem\MonoDevelopWorkspace.cs:line 385
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MonoDevelop.Ide.TypeSystem.MonoDevelopWorkspace.<HandleActiveConfigurationChanged>d__61.MoveNext() in E:\therzok\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.TypeSystem\MonoDevelopWorkspace.cs:line 384
```