[MacPlatform] Fix NRE
I've been getting this crash since I pulled latest master 2 days ago:

```
FATAL ERROR [2018-09-30 20:02:04Z]: Visual Studio failed to start
System.NullReferenceException: Object reference not set to an instance of an object
  at MonoDevelop.MacIntegration.MainToolbar.SelectorView+PathSelectorView.BecomeFirstResponder () [0x0000c] in /Users/rodrigo/Projects/xamarin/monodevelop/main/src/addins/MacPlatform/MainToolbar/SelectorView.cs:635
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) ObjCRuntime.Messaging.bool_objc_msgSend_IntPtr(intptr,intptr,intptr)
  at AppKit.NSWindow.MakeFirstResponder (AppKit.NSResponder aResponder) [0x00012] in /Library/Frameworks/Xamarin.Mac.framework/Versions/4.8.0.22/src/Xamarin.Mac/AppKit/NSWindow.g.cs:3230
  at MonoDevelop.MacIntegration.MainToolbar.SelectorView.BecomeFirstResponder () [0x0001b] in /Users/rodrigo/Projects/xamarin/monodevelop/main/src/addins/MacPlatform/MainToolbar/SelectorView.cs:135
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSendSuper_bool(intptr,intptr,bool)
  at AppKit.NSCell.set_Enabled (System.Boolean value) [0x00028] in /Library/Frameworks/Xamarin.Mac.framework/Versions/4.8.0.22/src/Xamarin.Mac/AppKit/NSCell.g.cs:7038
  at MonoDevelop.MacIntegration.MainToolbar.ColoredButtonCell.DrawInteriorWithFrame (CoreGraphics.CGRect cellFrame, AppKit.NSView inView) [0x0007a] in /Users/rodrigo/Projects/xamarin/monodevelop/main/src/addins/MacPlatform/MainToolbar/RunButton.cs:229
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) Gtk.Application.gtk_events_pending()
  at Gtk.Application.EventsPending () [0x00001] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/external/bockbuild/builds/gtk-sharp-None/gtk/Application.cs:153
  at MonoDevelop.Ide.DispatchService.RunPendingEvents () [0x00065] in /Users/rodrigo/Projects/xamarin/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DispatchService.cs:185
  at MonoDevelop.Ide.IdeApp.Initialize (MonoDevelop.Core.ProgressMonitor monitor) [0x001ea] in /Users/rodrigo/Projects/xamarin/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs:262
  at MonoDevelop.Ide.IdeStartup.Run (MonoDevelop.Ide.MonoDevelopOptions options) [0x00717] in /Users/rodrigo/Projects/xamarin/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs:281
```

Not sure what the root cause is (I guess this being called before main loop
is setup?), but this fixes it for me.