[Core] Fix stack overflow when using AsyncCriticalSection (#7324)
If many tasks call DotNetProject.RunResolveAssemblyReferencesTarget
then they can all be queued with an AsyncCriticalSection. When the
AsyncCriticalSection is disposed it calls TaskCompletionSource's
TrySetResult. If there are many queued items this can result in a
stackoverflow if the continuations are run synchronously. To prevent
this the TaskCompletionSource is created with the TaskCreationOptions
set to RunContinuationsAsynchronously.

https://stackoverflow.com/questions/28321457/taskcontinuationoptions-runcontinuationsasynchronously-and-stack-dives

System.StackOverflowException: The requested operation caused a stack overflow.
  at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action action, System.Boolean allowInlining, System.Threading.Tasks.Task& currentTask) [0x00022]
  in mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:684
  at System.Threading.Tasks.Task.FinishContinuations () [0x00052]
  in mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:3198
  at System.Threading.Tasks.Task.FinishStageThree () [0x0003c]
  in mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2247
  at System.Threading.Tasks.Task`1[TResult].TrySetResult (TResult result) [0x0004f]
  in mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:433
  at System.Threading.Tasks.TaskCompletionSource`1[TResult].TrySetResult (TResult result) [0x00000]
  in mono-x64/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/TaskCompletionSource.cs:274
  at System.Threading.Tasks.TaskCompletionSource`1[TResult].SetResult (TResult result) [0x00000]
  in mono-x64/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/TaskCompletionSource.cs:297
  at MonoDevelop.Projects.AsyncCriticalSection.Exit () [0x00042]
  in main/src/core/MonoDevelop.Core/MonoDevelop.Projects/AsyncCriticalSection.cs:86
  at MonoDevelop.Projects.AsyncCriticalSection+CriticalSectionDisposer.Dispose () [0x00000]
  in main/src/core/MonoDevelop.Core/MonoDevelop.Projects/AsyncCriticalSection.cs:45
  at MonoDevelop.Projects.DotNetProject.RunResolveAssemblyReferencesTarget (MonoDevelop.Projects.ConfigurationSelector configuration) [0x00237]
  in main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs:1079

Fixes VSTS #814631 - Instant crashes