[VCS] Add proper cache invalidation for repository references
This fixes bugs that arise from the now fixed memory leaks that
retained solutions/projects. An user would not be able to do any
filesystem extension operations due ot the fact that the repository was
disposed and the cache wasn't properly invalidated.

The cache would hold the repository reference inside the project
entry's properties so it could not be cleared whatever else happened.

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'handle'.
at System.Runtime.InteropServices.SafeHandle.DangerousAddRef
(System.Boolean& success) [0x00020] in
  /private/tmp/source-mono-master/bockbuild-xamarin/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/corlib/System.Runtime.InteropServices/SafeHandle.cs:120
at (wrapper managed-to-native)
  LibGit2Sharp.Core.NativeMethods:git_reference_lookup
(LibGit2Sharp.Core.Handles.ReferenceSafeHandle&,LibGit2Sharp.Core.Handles.RepositorySafeHandle,string)
  at LibGit2Sharp.Core.Proxy.git_reference_lookup
  (LibGit2Sharp.Core.Handles.RepositorySafeHandle repo,
   System.String name, Boolean shouldThrowIfNotFound) [0x00000] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/external/libgit2sharp/LibGit2Sharp/Core/Proxy.cs:1800
  at LibGit2Sharp.ReferenceCollection.RetrieveReferencePtr
(System.String referenceName, Boolean shouldThrowIfNotFound)
  [0x00000] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/external/libgit2sharp/LibGit2Sharp/ReferenceCollection.cs:678
  at LibGit2Sharp.ReferenceCollection.Resolve[T] (System.String
                                                  name) [0x0000b] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/external/libgit2sharp/LibGit2Sharp/ReferenceCollection.cs:442
  at LibGit2Sharp.ReferenceCollection.get_Item (System.String
                                                name) [0x00000] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/external/libgit2sharp/LibGit2Sharp/ReferenceCollection.cs:42
  at LibGit2Sharp.ReferenceCollection.get_Head () [0x00000]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/external/libgit2sharp/LibGit2Sharp/ReferenceCollection.cs:705
  at LibGit2Sharp.Repository.get_Head () [0x00000] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/external/libgit2sharp/LibGit2Sharp/Repository.cs:219
  at
  MonoDevelop.VersionControl.Git.GitRepository.GetHeadCommit
  (LibGit2Sharp.Repository repository) [0x00000] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs:142
  at
  MonoDevelop.VersionControl.Git.GitRepository.GetDirectoryVersionInfo
  (FilePath localDirectory, IEnumerable`1
   localFileNames, Boolean getRemoteStatus, Boolean
   recursive) [0x00134] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs:420
  at
  MonoDevelop.VersionControl.Git.GitRepository.OnGetVersionInfo
(IEnumerable`1 paths, Boolean getRemoteStatus)
  [0x00000] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs:380
  at
  MonoDevelop.VersionControl.Repository.GetVersionInfo
  (IEnumerable`1 paths, VersionInfoQueryFlags
   queryFlags) [0x00008] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs:234
  at
  MonoDevelop.VersionControl.VersionControlService.OnFileAdded
(System.Object s,
 MonoDevelop.Projects.ProjectFileEventArgs e)
  [0x000ae] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs:483
at (wrapper delegate-invoke)
  <Module>:invoke_void_object_ProjectFileEventArgs
(object,MonoDevelop.Projects.ProjectFileEventArgs)
  at
  MonoDevelop.Ide.RootWorkspace.NotifyFileAddedToProject
  (System.Object sender,
   MonoDevelop.Projects.ProjectFileEventArgs
   e) [0x0000b] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs:1022
  at
  MonoDevelop.Projects.Solution.OnFileAddedToProject
  (MonoDevelop.Projects.ProjectFileEventArgs
   args) [0x0000b] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Solution.cs:1021
  at
  MonoDevelop.Projects.SolutionFolder.OnFileAddedToProject
  (MonoDevelop.Projects.ProjectFileEventArgs
   e) [0x00016] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolder.cs:929
  at
  MonoDevelop.Projects.SolutionFolder.NotifyFileAddedToProject
  (System.Object sender,
   MonoDevelop.Projects.ProjectFileEventArgs
   e) [0x00000] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolder.cs:796
  at
  MonoDevelop.Projects.SolutionFolder.OnFileAddedToProject
  (MonoDevelop.Projects.ProjectFileEventArgs
   e) [0x0002d] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolder.cs:931
  at
  MonoDevelop.Projects.SolutionFolder.NotifyFileAddedToProject
  (System.Object sender,
   MonoDevelop.Projects.ProjectFileEventArgs
   e) [0x00000] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolder.cs:796
at (wrapper delegate-invoke)
  <Module>:invoke_void_object_ProjectFileEventArgs
(object,MonoDevelop.Projects.ProjectFileEventArgs)
  at
  MonoDevelop.Projects.Project.DoOnFileAddedToProject
  (MonoDevelop.Projects.ProjectFileEventArgs
   e) [0x00012] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:2794
  at
  MonoDevelop.Projects.Project+DefaultMSBuildProjectExtension.OnFileAddedToProject
  (MonoDevelop.Projects.ProjectFileEventArgs
   e) [0x00000] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:2947
  at
  MonoDevelop.Projects.ProjectExtension.OnFileAddedToProject
  (MonoDevelop.Projects.ProjectFileEventArgs
   e) [0x00000] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectExtension.cs:197
  at
  MonoDevelop.Projects.ProjectExtension.OnFileAddedToProject
  (MonoDevelop.Projects.ProjectFileEventArgs
   e) [0x00000] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectExtension.cs:197
  at
  MonoDevelop.Projects.ProjectExtension.OnFileAddedToProject
  (MonoDevelop.Projects.ProjectFileEventArgs
   e) [0x00000] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectExtension.cs:197
  at
  MonoDevelop.Projects.ProjectExtension.OnFileAddedToProject
  (MonoDevelop.Projects.ProjectFileEventArgs
   e) [0x00000] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectExtension.cs:197
  at
  MonoDevelop.Projects.ProjectExtension.OnFileAddedToProject
  (MonoDevelop.Projects.ProjectFileEventArgs
   e) [0x00000] in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectExtension.cs:197
  at
  MonoDevelop.Projects.ProjectExtension.OnFileAddedToProject
  (MonoDevelop.Projects.ProjectFileEventArgs
   e) [0x00000]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectExtension.cs:197
  at
  MonoDevelop.Projects.ProjectExtension.OnFileAddedToProject
  (MonoDevelop.Projects.ProjectFileEventArgs
   e) [0x00000]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectExtension.cs:197
  at
  MonoDevelop.Projects.Project.OnFileAddedToProject
  (MonoDevelop.Projects.ProjectFileEventArgs
   e)
  [0x00000]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:2788
  at
  MonoDevelop.Projects.Project.NotifyFileAddedToProject
  (IEnumerable`1
   objs)
  [0x00061]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:1853
  at
  MonoDevelop.Projects.Project.OnItemsAdded
  (IEnumerable`1
   objs)
  [0x00064]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:1791
  at
  MonoDevelop.Projects.DotNetProject.OnItemsAdded
  (IEnumerable`1
   objs)
  [0x00000]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs:1369
  at
  MonoDevelop.Projects.ProjectItemCollection`1[T].NotifyAdded
  (IEnumerable`1
   items,
   Boolean
   comesFromParent)
  [0x0009a]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectItemCollection.cs:150
  at
  MonoDevelop.Projects.ProjectItemCollection`1[T].MonoDevelop.Projects.IItemListHandler.InternalAdd
  (IEnumerable`1
   items,
   Boolean
   comesFromParent)
  [0x00020]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectItemCollection.cs:120
  at
  MonoDevelop.Projects.ProjectItemCollection`1[T].NotifyAdded
  (IEnumerable`1
   items,
   Boolean
   comesFromParent)
  [0x00082]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectItemCollection.cs:148
  at
  MonoDevelop.Projects.ProjectItemCollection`1[T].OnItemsAdded
  (IEnumerable`1
   items)
  [0x00013]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectItemCollection.cs:98
  at
  MonoDevelop.Projects.ProjectFileCollection.OnItemsAdded
  (IEnumerable`1
   items)
  [0x00037]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectFileCollection.cs:194
  at
  MonoDevelop.Projects.ItemCollection`1[T].Add
  (MonoDevelop.Projects.T
   item)
  [0x00012]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ItemCollection.cs:64
  at
  MonoDevelop.Projects.Project.AddFile
  (System.String
   filename,
   System.String
   buildAction)
  [0x00069]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:1216
  at
  MonoDevelop.Ide.Templates.SingleFileDescriptionTemplate.AddFileToProject
  (MonoDevelop.Projects.SolutionFolderItem
   policyParent,
   MonoDevelop.Projects.Project
   project,
   System.String
   language,
   System.String
   directory,
   System.String
   name)
  [0x00038]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SingleFileDescriptionTemplate.cs:121
  at
  MonoDevelop.Ide.Templates.SingleFileDescriptionTemplate.AddToProject
  (MonoDevelop.Projects.SolutionFolderItem
   policyParent,
   MonoDevelop.Projects.Project
   project,
   System.String
   language,
   System.String
   directory,
   System.String
   name)
  [0x00000]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SingleFileDescriptionTemplate.cs:113
  at
  MonoDevelop.Ide.Templates.FileTemplate.CreateFile
  (MonoDevelop.Ide.Templates.FileDescriptionTemplate
   newfile,
   MonoDevelop.Projects.SolutionFolderItem
   policyParent,
   MonoDevelop.Projects.Project
   project,
   System.String
   directory,
   System.String
   language,
   System.String
   name)
  [0x00019]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileTemplate.cs:313
  at
  MonoDevelop.Ide.Templates.FileTemplate.Create
  (MonoDevelop.Projects.SolutionFolderItem
   policyParent,
   MonoDevelop.Projects.Project
   project,
   System.String
   directory,
   System.String
   language,
   System.String
   name)
  [0x0002b]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileTemplate.cs:254
  at
  MonoDevelop.Ide.Projects.NewFileDialog.OpenEvent
  (System.Object
   sender,
   System.EventArgs
   e)
  [0x000ab]
  in
  /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewFileDialog.cs:490