Disabling treat warnings on errors in VersionControl.Git.
On Windows when building we see an error:
C:\Temp\monodevelop\main\src\addins\VersionControl\MonoDevelop.VersionControl.Git\gtk-gui\generated.cs(17,17): Error CS0436: The type 'BinContainer' in 'C:\Temp\monodevelop\main\src\addins\VersionControl\MonoDevelop.VersionControl.Git\gtk-gui\generated.cs' conflicts with the imported type 'BinContainer' in 'MonoDevelop.SourceEditor, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b'. Using the type defined in 'C:\Temp\monodevelop\main\src\addins\VersionControl\MonoDevelop.VersionControl.Git\gtk-gui\generated.cs'. (CS0436) (MonoDevelop.VersionControl.Git)