[Startup] Fix SharpZipLib binding redirect
Fixed bug #44928 - Unable to add component from component store to
Android project on Windows.
https://bugzilla.xamarin.com/show_bug.cgi?id=44928

Any code that used the ICSharpCode.SharpZipLib assembly on Windows
would fail since the binding redirect specified a different
assembly version. The SharpZipLib assembly has the version 0.86.0.518
whilst the binding redirect specified 0.86.0.0 which resulted in the
following error when trying to unzip a component from the store:

System.IO.FileLoadException: Could not load file or assembly
'ICSharpCode.SharpZipLib, Version=0.86.0.0, Culture=neutral,
PublicKeyToken=1b03e6acf1164f73' or one of its dependencies.