When firing async events, clone the event to avoid a collection modification exception (#7291)
* When firing async events, clone the event to avoid a collection modification exception

```
ERROR [2019-02-28 23:20:50Z]: An unhandled exception has occurred. Terminating Visual Studio? False
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in <3c73e0665b1b47bb9d553430a97aa942>:0
  at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in <3c73e0665b1b47bb9d553430a97aa942>:0
  at MonoDevelop.Projects.Project+<>c__DisplayClass349_0.<OnFileDeleted>b__0 () [0x00031] in <500e8d32b687408f897daf1edbb52aa9>:0
  at MonoDevelop.Core.Runtime+<>c.<RunInMainThread>b__40_0 (System.Object state) [0x00015]
```

Instead of doing the clone conditionally, do it unconditionally. Doing it conditionally, can race
and re-introduce the exception

Fixes VSTS #806669 - FileService event reduction can cause exceptions in async events

* Move cloning support into AsyncEvents.

This makes the clone requirement contained and encapsulated in the AsyncEvents class and also avoids cloning the event args if the events are unused