[Core] Fix invalid file search pattern for path wildcard
A wildcard item include or update such as 'Properties\**' would cause
an ArgumentException to be thrown when searching for files on loading
the project. The search pattern passed to Directory.GetFiles was
'**/*' which invalid.

MSBuild project could not be evaluated
System.ArgumentException: Pattern is invalid
Parameter name: searchPattern
  at System.IO.Directory.ValidateDirectoryListing (System.String path, System.String searchPattern, System.Boolean& stop)
    in mono-x86/mcs/class/corlib/System.IO/Directory.cs:479
  at System.IO.Directory.GetFileSystemEntries (System.String path, System.String searchPattern, System.IO.FileAttributes mask, System.IO.FileAttributes attrs)
    in mono-x86/mcs/class/corlib/System.IO/Directory.cs:489
  at System.IO.Directory.GetFiles (System.String path, System.String searchPattern)
    in mono-x86/mcs/class/corlib/System.IO/Directory.cs:296
  at MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine.ExpandWildcardFilePath[T] (MonoDevelop.Projects.MSBuild.MSBuildProject project, MonoDevelop.Core.FilePath basePath, MonoDevelop.Core.FilePath baseRecursiveDir, System.Boolean recursive, System.String[] filePath, System.Int32 index, MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine+WildcardExpansionFunc`1[T] func)
    in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs:756
  at MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine.ExpandWildcardFilePath[T] (MonoDevelop.Projects.MSBuild.MSBuildProject project, MonoDevelop.Core.FilePath basePath, MonoDevelop.Core.FilePath baseRecursiveDir, System.Boolean recursive, System.String[] filePath, System.Int32 index, MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine+WildcardExpansionFunc`1[T] func)
    in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs:767
  at MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine.GetIncludesForWildcardFilePath (MonoDevelop.Projects.MSBuild.MSBuildProject project, System.String path)
    in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs:713
  at MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine.UpdateItem (MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine+ProjectInfo project, MonoDevelop.Projects.MSBuild.MSBuildItem item, System.String update, System.Boolean trueCond, MonoDevelop.Projects.MSBuild.MSBuildItemEvaluated it)
    in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs:312
  at MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine.Evaluate (MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine+ProjectInfo project, MonoDevelop.Projects.MSBuild.MSBuildEvaluationContext context, MonoDevelop.Projects.MSBuild.MSBuildItemGroup items)
    in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs:277