[Windows] Improve handling of missing files in Open File dialog.
One problem was selecting a file in the Open File dialog and then
opening another directory. The Open File dialog would try to check
that the selected file, which now would not exist in the new directory,
was a solution or project file. This check would try to read the file
resulting in a FileNotFoundException being logged:

System.IO.FileNotFoundException: Could not find file 'F:\projects\test\Resources\Test.sln'.
File name: 'F:\projects\test\Resources\Test.sln'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at MonoDevelop.Projects.Formats.MSBuild.SlnFileFormat.GetSlnFileVersion(String strInSlnFile, String& headerComment)
   at MonoDevelop.Projects.Formats.MSBuild.SlnFileFormat.CanReadFile(String file, MSBuildFileFormat format)
   at MonoDevelop.Projects.Formats.MSBuild.MSBuildFileFormat.CanReadFile(FilePath file, Type expectedType)
   at MonoDevelop.Projects.FileFormatManager.GetFileFormats(String fileName, Type expectedType)
   at MonoDevelop.Projects.ProjectService.IsWorkspaceItemFileInternal(String filename)
   at MonoDevelop.Projects.DefaultProjectServiceExtension.IsWorkspaceItemFile(String filename)
   at MonoDevelop.Projects.ProjectServiceExtension.IsWorkspaceItemFile(String fileName)
   at MonoDevelop.Projects.ProjectServiceExtension.IsWorkspaceItemFile(String fileName)
   at MonoDevelop.Projects.ProjectServiceExtension.IsWorkspaceItemFile(String fileName)
   at MonoDevelop.Projects.ProjectServiceExtension.IsWorkspaceItemFile(String fileName)
   at MonoDevelop.Projects.ProjectServiceExtension.IsWorkspaceItemFile(String fileName)
   at MonoDevelop.Projects.ProjectServiceExtension.IsWorkspaceItemFile(String fileName)
   at MonoDevelop.Projects.ProjectServiceExtension.IsWorkspaceItemFile(String fileName)
   at MonoDevelop.Projects.ProjectService.IsWorkspaceItemFile(String filename)
   at MonoDevelop.Platform.OpenFileDialogHandler.FillViewers(CustomCommonFileDialogComboBox combo, String fileName)
   at MonoDevelop.Platform.OpenFileDialogHandler.<>c__DisplayClass9.<Run>b__5(Object sender, EventArgs e)

Another problem was that it was possible to enter a solution filename
that did not exist. In this case clicking the Open button would close
the dialog but nothing would happen. In the log you would see:

Error while executing command: Open...
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Collections.ObjectModel.Collection`1.get_Item(Int32 index)
   at MonoDevelop.Platform.OpenFileDialogHandler.Run(OpenFileDialogData data)
   at MonoDevelop.Components.Extensions.PlatformDialog`1.Run()
   at MonoDevelop.Components.Extensions.SelectFileDialog`1.Run()
   at MonoDevelop.Ide.Commands.OpenFileHandler.Run()
   at MonoDevelop.Components.Commands.CommandHandler.Run(Object dataItem)
   at MonoDevelop.Components.Commands.CommandHandler.InternalRun(Object dataItem)
   at MonoDevelop.Components.Commands.CommandManager.DefaultDispatchCommand(ActionCommand cmd, CommandInfo info, Object dataItem, Object target, CommandSource source)
   at MonoDevelop.Components.Commands.CommandManager.DispatchCommand(Object commandId, Object dataItem, Object initialTarget, CommandSource source)

Now the File to Open dialog has EnsureFileExists set to true so if
the file does not exist then the dialog will show a file not found
message box.