[NuGet] Fixed null ref when updating a NuGet package.
Fixed bug #31219 - Null reference when updating a NuGet package
https://bugzilla.xamarin.com/show_bug.cgi?id=31219

When right clicking a package reference and updating, reinstalling or
removing, occasionally the ProjectOperations.CurrentSelectedProject is
null causing a null reference exception.

System.NullReferenceException: Object reference not set to an instance of an object
  at MonoDevelop.PackageManagement.UpdatedPackagesMonitor.RegisterProjectEvents () [0x00029] in main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/UpdatedPackagesMonitor.cs:54
  at MonoDevelop.PackageManagement.UpdatedPackagesMonitor..ctor (IEnumerable`1 projects) [0x00014] in main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/UpdatedPackagesMonitor.cs:48
  at MonoDevelop.PackageManagement.UpdatePackagesProgressMonitorStatusMessage..ctor (IEnumerable`1 projects, System.String packagesUpToDateMessage, System.String packagesUpToDateWarningMessage, MonoDevelop.PackageManagement.ProgressMonitorStatusMessage message) [0x00033] in main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/UpdatePackagesProgressMonitorStatusMessage.cs:61
  at MonoDevelop.PackageManagement.UpdatePackagesProgressMonitorStatusMessage..ctor (IPackageManagementProject project, System.String packagesUpToDateMessage, System.String packagesUpToDateWarningMessage, MonoDevelop.PackageManagement.ProgressMonitorStatusMessage message) [0x00000] in main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/UpdatePackagesProgressMonitorStatusMessage.cs:44
  at MonoDevelop.PackageManagement.ProgressMonitorStatusMessageFactory.CreateUpdatingSinglePackageMessage (System.String packageId, IPackageManagementProject project) [0x0001f] in main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProgressMonitorStatusMessageFactory.cs:129
  at MonoDevelop.PackageManagement.Commands.PackageReferenceNodeCommandHandler.UpdatePackage () [0x00033] in main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Commands/PackageReferenceNodeCommandHandler.cs:90

Since the package reference itself is associated with a project the
NuGet addin now uses this project rather than the current project as
defined by the IdeApp.ProjectOperations.CurrentSelectedProject.