Properly set OutputKind on CSharpCompilationOptions.
Extenders who might request the Roslyn Compilation from a project and inspect the diagnostics may find an error CS7088 "Main method is missing" because the project is actually a .dll but we're setting OutputKind.ConsoleApplication in CSharpCompilationOptions.