[Ide] Fix project being loaded into remote build engine multiple times
When a new project is added to an existing solution, and the project
template uses the old templating engine, if the project template uses
a relative path in the template (e.g. "./Droid" or "./iOS") this would
result in the project's filename including the "./" part of this
path. This filename is then passed in the ProjectConfigurationInfo
which is passed to the remote MSBuild host. The MSBuild build engine
normalizes the filename after the project has been loaded so this
results in the project being loaded again into the build engine since
there is no match for the filename with the "./" in its path. This then
causes a failure in the MSBuild host:

System.Exception: MSBuild operation failed --->
System.InvalidOperationException: An equivalent project (a project with
the same global properties and tools version) is already present in the
project collection, with the path
"buildtemplates/iOS/Xamarin.Forms.FSharp.FormsApp.iOS.fsproj". To load
an equivalent into this project collection, unload this project first.

This was also causing the F# template tests to fail. This was happening
in the F# tests when the global property was set for the Platform which
causes MSBuild to remove and then re-add the project back again but
using the normalized filename which already exists.