[Ide] Fix null reference when document has no editor.
Fixed bug #38833  - Getting error Error adding to project: object
reference not set to an instance of an object when adding component.
https://bugzilla.xamarin.com/show_bug.cgi?id=38833

On adding a Xamarin Component to a project a reference may be added
to the project. This then triggers a reparse of the document,
including the document associated with the component's view content
which has no associated editor so a null reference occurred when the
editor was used without checking if it was null. This problem was
introduced by commit fa99d4d91344139f3f00d787b89f18a272da7269

System.NullReferenceException: Object reference not set to an instance of an object

Server stack trace:
   at MonoDevelop.Ide.Gui.Document.GetCurrentParseFileName () in monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs:891
   at MonoDevelop.Ide.Gui.Document.StartReparseThread () in monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs:877
   at MonoDevelop.Ide.Gui.Document.HandleProjectModified (System.Object sender, MonoDevelop.Projects.SolutionItemModifiedEventArgs e) in monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs:730
   at (wrapper delegate-invoke) <Module>:invoke_void_object_SolutionItemModifiedEventArgs (object,MonoDevelop.Projects.SolutionItemModifiedEventArgs)
   at MonoDevelop.Projects.SolutionFolderItem.OnModified (MonoDevelop.Projects.SolutionItemModifiedEventArgs args) in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolderItem.cs:445
   at MonoDevelop.Projects.Project.OnModified (MonoDevelop.Projects.SolutionItemModifiedEventArgs args) in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:320
   at MonoDevelop.Projects.SolutionFolderItem.NotifyModified (System.String hint) in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolderItem.cs:432
   at MonoDevelop.Projects.DotNetProject.NotifyReferenceAddedToProject (MonoDevelop.Projects.ProjectReference reference) in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs:1453
   at MonoDevelop.Projects.DotNetProject.OnItemsAdded (IEnumerable`1 objs) in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs:1431
   at MonoDevelop.Projects.ProjectItemCollection`1[T].NotifyAdded (IEnumerable`1 items, Boolean comesFromParent) in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectItemCollection.cs:150
   at MonoDevelop.Projects.ProjectItemCollection`1[T].MonoDevelop.Projects.IItemListHandler.InternalAdd (IEnumerable`1 items, Boolean comesFromParent) in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectItemCollection.cs:120
   at MonoDevelop.Projects.ProjectItemCollection`1[T].NotifyAdded (IEnumerable`1 items, Boolean comesFromParent) in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectItemCollection.cs:148
   at MonoDevelop.Projects.ProjectItemCollection`1[T].OnItemsAdded (IEnumerable`1 items) in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectItemCollection.cs:98
   at MonoDevelop.Projects.ItemCollection`1[T].Add (MonoDevelop.Projects.T item)  in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ItemCollection.cs:64
   at MonoDevelop.Projects.DotNetProject.AddReference (System.String filename)  in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs:807