[NuGet] Fix Add Packages dialog not opend when show pre-release used
Fixed ArgumentNullException when setting the show pre-release flag in
the Add Packages dialog before the dialog is shown due to the package
source list being null.

System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at MonoDevelop.PackageManagement.AllPackagesViewModel.get_SelectedPackageSource() in main\src\addins\MonoDevelop.PackageManagement\MonoDevelop.PackageManagement\AllPackagesViewModel.cs:line 82
   at MonoDevelop.PackageManagement.AllPackagesViewModel.ReadPackages() in main\src\addins\MonoDevelop.PackageManagement\MonoDevelop.PackageManagement\AllPackagesViewModel.cs:line 137
   at MonoDevelop.PackageManagement.AllPackagesViewModel.set_IncludePrerelease(Boolean value) in main\src\addins\MonoDevelop.PackageManagement\MonoDevelop.PackageManagement\AllPackagesViewModel.cs:line 110
   at MonoDevelop.PackageManagement.AddPackagesDialog.LoadViewModel(String initialSearch) in main\src\addins\MonoDevelop.PackageManagement\MonoDevelop.PackageManagement.Gui\AddPackagesDialog.cs:line 221
   at MonoDevelop.PackageManagement.AddPackagesDialog..ctor(AllPackagesViewModel viewModel, String initialSearch, IBackgroundPackageActionRunner backgroundActionRunner, IRecentPackageRepository recentPackageRepository) in main\src\addins\MonoDevelop.PackageManagement\MonoDevelop.PackageManagement.Gui\AddPackagesDialog.cs:line 89
   at MonoDevelop.PackageManagement.AddPackagesDialog..ctor(AllPackagesViewModel viewModel, String initialSearch) in main\src\addins\MonoDevelop.PackageManagement\MonoDevelop.PackageManagement.Gui\AddPackagesDialog.cs:line 64
   at MonoDevelop.PackageManagement.AddPackagesDialogRunner.CreateDialog(String initialSearch) in main\src\addins\MonoDevelop.PackageManagement\MonoDevelop.PackageManagement.Gui\AddPackagesDialogRunner.cs:line 58
   at MonoDevelop.PackageManagement.AddPackagesDialogRunner.Run(String initialSearch) in main\src\addins\MonoDevelop.PackageManagement\MonoDevelop.PackageManagement.Gui\AddPackagesDialogRunner.cs:line 40