[Core] Fix error building projects on Windows.
If MSBuild 15 is not installed on Windows then it was not possible to
build any project type that requires MSBuild.

System.Exception: Did not find MSBuild for runtime MS.NET
   at MonoDevelop.Projects.MSBuild.MSBuildProjectService.GetNewestInstalledToolsVersion()
   in main\src\core\MonoDevelop.Core\MonoDevelop.Projects.MSBuild\MSBuildProjectService.cs:line 888
   at MonoDevelop.Projects.MSBuild.MSBuildProjectService.<GetProjectBuilder>d__82.MoveNext()
   in main\src\core\MonoDevelop.Core\MonoDevelop.Projects.MSBuild\MSBuildProjectService.cs:line 900