[Debugger.Soft] Stop referencing Mono.Cecil.Mdb, to fix mono 2.10.x build
When trying to build MonoDevelop master with stock Mono from Ubuntu 12.10
packages (2.10.8.1), a compiler error would happen:

SoftDebuggerSession.cs(59,36): error CS0433: The imported type
`Mono.CompilerServices.SymbolWriter.MonoSymbolFile' is defined multiple times
/.../monodevelop/main/external/cecil/bin/net_4_0_Debug/Mono.Cecil.Mdb.dll
(Location of the symbol related to previous error)
/.../monodevelop/main/build/bin/ICSharpCode.NRefactory.CSharp.dll
(Location of the symbol related to previous error)

Mono.Cecil.Mdb was indeed an unused reference. This fixes BXC#11134.