[Core] Fix null reference accessing target framework monikers
Creating a .NET Core console project, then adding a new non-SDK style
C# library project, it was not possible to open the Edit References
dialog for the library project. The IDE log would have a null
reference exception:

System.NullReferenceException: Object reference not set to an instance of an object
  at System.Collections.Immutable.ImmutableArray`1[T].ThrowNullRefIfNotInitialized () [0x00000] in <6518d0e60ca84f6b915c07341a031a32>:0
  at System.Collections.Immutable.ImmutableArray`1[T].GetEnumerator () [0x00007] in <6518d0e60ca84f6b915c07341a031a32>:0
  at MonoDevelop.PackageManagement.PackageManagementCanReferenceProjectExtension.CanReferenceProject

The problem was that the project's TargetFramework setter is not
called when adding a new project to an existing solution so the
project's TargetFrameworkMonikers array was not initialized. This is
now handled.

Fixes VSTS #973344 - Unable to open Edit References dialog for new
project