[NuGet] Fix tests failing to load in Unit Tests window
Removed local MonoDevelop.Ide copy which was causing a type load
exception.

System.TypeLoadException: Could not load type of field
'MonoDevelop.PackageManagement.Tests.ItemTemplateNuGetPackageInstallerTests:installer' (0)
due to: Could not load file or assembly 'MonoDevelop.Ide,
Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b'
or one of its dependencies.