[Ide] Ensure MSBuild 15 assemblies are resolved on startup
MonoDevelop.Ide now uses MSBuild 15 assemblies which are shipped with
Mono but not included with the IDE. The MSBuild 15 assemblies are not
in the GAC so they need to be resolved from the correct location.
Whilst Runtime.Initialize loads these MSBuild 15 assemblies this
seems to happen too late and results in a fatal exception when the
MEF composition fails to resolve the Microsoft.Build assembly.

System.ApplicationException: MEF catalog scanning errors encountered.
Microsoft.VisualStudio.Composition.PartDiscoveryException: Failure while scanning type
"MonoDevelop.Ide.BuildOutputView.MSBuildOutputProcessor". --->
System.TypeLoadException: Could not load type of field 'MonoDevelop.Ide.BuildOutputView.MSBuildOutputProcessor:binlogReader' (0) due to:
Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

Now early on during startup an assembly resolver is added and used to
resolve the MSBuild 15 assemblies. This also fixes other startup
warnings about being unable to find the MSBuild 15 assemblies
and the registrar failing to register the MonoDevelop.Ide assembly.

Could not register the assembly 'MonoDevelop.Ide': System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in mono-x64/mcs/class/corlib/System.Reflection/Assembly.cs:410
  at Registrar.DynamicRegistrar.CollectTypes (System.Reflection.Assembly assembly) in xamarin-macios/src/ObjCRuntime/DynamicRegistrar.cs:237
  at Registrar.Registrar.RegisterAssembly (System.Reflection.Assembly assembly) in xamarin-macios/src/ObjCRuntime/Registrar.cs:2279