[Core] Fix MSBuildEngineManager disposed error
Dispose the MSBuildEngineManager after the project active tasks have
completed. This should avoid the MSBuildEngineManager being used
by the project after it has been disposed. Also prevent new tasks
being bound in BindTask once the dispose has started. If BindTask
is called when a dispose has started for a parent object a
cancelled task is returned from BindTask.

  System.ObjectDisposedException: Cannot access a disposed object.
  Object name: 'MSBuildEngineManager'.
    at MonoDevelop.Projects.MSBuild.MSBuildEngineManager.GetEngine (System.Boolean supportsMSBuild) [0x0001e] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEngineManager.cs:55
    at MonoDevelop.Projects.MSBuild.MSBuildProject.LoadNativeInstance (System.Boolean evaluateItems) [0x0005b] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs:498
    at MonoDevelop.Projects.MSBuild.MSBuildProjectInstance.Evaluate () [0x00019] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectInstance.cs:92
    at MonoDevelop.Projects.ProjectRunConfiguration.Initialize (MonoDevelop.Projects.Project project) [0x00038] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectRunConfiguration.cs:52
    at MonoDevelop.Projects.AssemblyRunConfiguration.Initialize (MonoDevelop.Projects.Project project) [0x00001] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/AssemblyRunConfiguration.cs:49
    at MonoDevelop.DotNetCore.DotNetCoreRunConfiguration.Initialize (MonoDevelop.Projects.Project project) [0x00019] in monodevelop/main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRunConfiguration.cs:87
    at MonoDevelop.Projects.Project.CreateRunConfigurationInternal (System.String name) [0x00009] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:343
    at MonoDevelop.Projects.Project.WriteRunConfigurations (MonoDevelop.Core.ProgressMonitor monitor, MonoDevelop.Projects.MSBuild.MSBuildProject msproject, MonoDevelop.Projects.MSBuild.IMSBuildPropertySet globalGroup) [0x00043] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:3444
    at MonoDevelop.Projects.Project.OnWriteProject (MonoDevelop.Core.ProgressMonitor monitor, MonoDevelop.Projects.MSBuild.MSBuildProject msproject) [0x00045] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:3299
    at MonoDevelop.Projects.DotNetProject.OnWriteProject (MonoDevelop.Core.ProgressMonitor monitor, MonoDevelop.Projects.MSBuild.MSBuildProject msproject) [0x00001] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs:2037

Fixes VSTS #797958 - MSBuildEngineManager disposed error