[Windows] Fix assemblies being copied to tests directory.
Set local copy to false for WindowsPlatform and MonoDevelop.Core
reference. Previously with the assemblies being copied into the tests
directory this was causing the NuGet addin tests to fail to load in
the Unit Tests window with a TypeLoadException:

System.TypeLoadException: Method 'get_DotNetProject' in type 'MonoDevelop.PackageManagement.Tests.Helpers.FakePackageManagementProject' from assembly 'MonoDevelop.PackageManagement.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.