[AspNet] Fix Add View/Controller dialog not being displayed.
Fixed bug #29325 - Views->Add->View...' context menu item does not
always work in ASP.NET MVC projects
https://bugzilla.xamarin.com/show_bug.cgi?id=29325

To reproduce:

1) Open Xamarin Studio.
2) Select ‘New Solution…’  And select ‘ASP.NET -> Empty ASP .NET MVC
Project’ (or 'ASP .NET MVC Project') Finish creating the solution.
3) Expand the project item in the Solution pad.
4) Right click on the ‘Views’ folder and select ‘Add->View…’

The expected Add View dialog will *usually* not appear. In the log
there is a FileNotFoundException:

Error while executing command: View...
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.IO.FileNotFoundException: Could not load file or assembly
'MonoDevelop.TextTemplating, Version=2.6.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at MonoDevelop.AspNet.Commands.AddViewFromControllerCommandHandler.AddView(AspNetAppProject project, String path, String name)
   at MonoDevelop.AspNet.ProjectPad.AspNetFolderNodeCommandHandler.AddView() in monodevelop\main\src\addins\AspNet\ProjectPad\AspNetFolderNodeCommandHandler.cs:line 152

Now the ASP.NET addin indicates that it depends on the TextTemplating
addin to ensure the MonoDevelop.TextTemplating assembly is loaded when
the ASP.NET addin is used.