[Mac] Fix possible crasher when debugging unit test
Haven't managed to reproduce it, from this trace:

```
FATAL ERROR [2018-05-10 09:48:33Z]: Visual Studio failed to start. Some of the assemblies required to run Visual Studio (for example gtk-sharp)may not be properly installed in the GAC.
System.InvalidOperationException: Sequence contains no matching element
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00012] in /Users/builder/data/lanes/5533/mono-mac-sdk/external/bockbuild/builds/mono-x64/external/corefx/src/System.Linq/src/System/Linq/First.cs:30
  at MonoDevelop.MacIntegration.MainToolbar.ButtonBar.<.ctor>b__5_5 (System.Object sender, System.EventArgs e) [0x00000] in /Users/builder/data/lanes/5810/5af3e985/source/monodevelop/main/src/addins/MacPlatform/MainToolbar/ButtonBar.cs:140
  at AppKit.ActionDispatcher.OnActivated (Foundation.NSObject sender) [0x00015] in /Users/builder/data/lanes/1381/d0bb1c5d/source/xamarin-macios/src/AppKit/ActionDispatcher.cs:49
  at (wrapper managed-to-native) Gtk.Application.gtk_main()
  at Gtk.Application.Run () [0x00001] in /Users/builder/data/lanes/5533/mono-mac-sdk/external/bockbuild/builds/gtk-sharp-None/gtk/Application.cs:145
  at MonoDevelop.Ide.IdeApp.Run () [0x00006] in /Users/builder/data/lanes/5810/5af3e985/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs:404
  at MonoDevelop.Ide.IdeStartup.Run (MonoDevelop.Ide.MonoDevelopOptions options) [0x00764] in /Users/builder/data/lanes/5810/5af3e985/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs:300
  at MonoDevelop.Ide.IdeStartup.Main (System.String[] args, MonoDevelop.Ide.Extensions.IdeCustomizer customizer) [0x0008f] in /Users/builder/data/lanes/5810/5af3e985/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs:619
```

It seems like there is no matching item for the item in the button bar.

Possibly, either the indexMap is empty or it was trying to use one of the toggle-able buttons (pause/resume), in the
wrong states.

Either way, guard against it.