Revert "Fixed 'Bug 44384 - Rename refactoring on constructor should rename"
This reverts commit e9adf2b5eaee5ba85bc71c294f681fa5cc69bdab.
This broke the build:

`error CS0019: Operator '==' cannot be applied to operands of type 'SymbolAndProjectId' and '<null>'`