[Core] Fix invalid search pattern with forward slash wildcard items
Wildcard items that had an Include or Update that used forward slashes,
such as '**/*.cs', would throw an ArgumentException due to an invalid
search pattern being used to search for files.

MSBuild project could not be evaluated
System.ArgumentException: Pattern is invalid
Parameter name: searchPattern
  at System.IO.Directory.ValidateDirectoryListing (System.String path, System.String searchPattern, System.Boolean& stop)
    in /mono-x86/mcs/class/corlib/System.IO/Directory.cs:473
  at System.IO.Directory.GetFileSystemEntries (System.String path, System.String searchPattern, System.IO.FileAttributes mask, System.IO.FileAttributes attrs)
    in /mono-x86/mcs/class/corlib/System.IO/Directory.cs:489
  at System.IO.Directory.GetFiles (System.String path, System.String searchPattern)
    in /mono-x86/mcs/class/corlib/System.IO/Directory.cs:296
  at MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine.ExpandWildcardFilePath[T] (MonoDevelop.Projects.MSBuild.MSBuildProject project, MonoDevelop.Core.FilePath basePath, MonoDevelop.Core.FilePath baseRecursiveDir, System.Boolean recursive, System.String[] filePath, System.Int32 index, MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine+WildcardExpansionFunc`1[T] func)
   in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs:756
 at MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine.ExpandWildcardFilePath (MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine+ProjectInfo pinfo, MonoDevelop.Projects.MSBuild.MSBuildEvaluationContext context, MonoDevelop.Projects.MSBuild.MSBuildItem sourceItem, System.String path)
   in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs:701
 at MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine.AddItem (MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine+ProjectInfo project, MonoDevelop.Projects.MSBuild.MSBuildEvaluationContext context, MonoDevelop.Projects.MSBuild.MSBuildItem item, MonoDevelop.Projects.MSBuild.MSBuildItemEvaluated it, System.String include, System.Text.RegularExpressions.Regex excludeRegex, System.Boolean trueCond)
   in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs:376
 at MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine.Evaluate (MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine+ProjectInfo project, MonoDevelop.Projects.MSBuild.MSBuildEvaluationContext context, MonoDevelop.Projects.MSBuild.MSBuildItemGroup items)
   in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs:300