Bump to a heapshot that can compile with mono 4.3.1+
Bypass this build error:
```CSC: error CS7064: Error opening icon file `.'. Access to the path '.' is denied.````