[UnitTests] Ignore failing test on Mono.
One of the Runtime.RunInMainThread tests fails on Mono with an
InvalidProgramException so the test is now ignored.

  InvalidProgramException: Invalid IL code in
MonoDevelop.Core.RuntimeTests/<RunInMainThreadWithAsyncFuncTask>c__AnonStorey23:<>m__0 (): IL_0003: stfld     0x040008be
  at MonoDevelop.Core.Runtime+<RunInMainThread>c__AnonStorey5.<>m__0 (System.Object ) [0x0000d] in
 monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs:407