[AspNet] Fix unit test projects not compiling when created.
Fixed bug #36096 - CSC: error CS2008: No files to compile were
specified - when building unit test project.
https://bugzilla.xamarin.com/show_bug.cgi?id=36096

The unit test projects were created without any C# files. This causes
the build to fail on Mono but works on Windows. Now the unit test
projects include a test class so they compile after being created.