[GtkCore] Fix null ref when adding Gtk# file to project.
Fixed bug #30457 - NRE when adding file
https://bugzilla.xamarin.com/show_bug.cgi?id=30457

A null reference exception would be thrown when adding any GTK# file
to a project that had did not have a gtk-sharp reference.

Adding a GTK# file would add a gtk-sharp and a gdk-sharp reference to
the project but would not set ExtendedProperties["GtkReferenceExists"]
to true for the project. This then caused the GtkDesignInfo to create
a GuiBuilderProject with a null filename. The null filename causes the
GuiBuilderProject to return a null SteticProject which was the cause
of the null reference exception, as shown below:

System.NullReferenceException: Object reference not set to an instance of an object.
   at MonoDevelop.GtkCore.GuiBuilder.GuiBuilderProject.AddNewComponent(XmlElement element) in main\src\addins\MonoDevelop.GtkCore\MonoDevelop.GtkCore.GuiBuilder\GuiBuilderProject.cs:line 268
   at MonoDevelop.GtkCore.WidgetFileDescriptionTemplate.AddToProject(SolutionItem policyParent,
Project project, String language, String directory, String name) in
main\src\addins\MonoDevelop.GtkCore\MonoDevelop.GtkCore\WidgetFileDescriptionTemplate.cs:line 115
   at MonoDevelop.Ide.Templates.FileTemplate.CreateFile(FileDescriptionTemplate newfile,
SolutionItem policyParent, Project project, String directory, String language, String name) in main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.Templates\FileTemplate.cs:line 370
   at MonoDevelop.Ide.Templates.FileTemplate.Create(SolutionItem policyParent, Project project,
String directory, String language, String name) in main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.Templates\FileTemplate.cs:line 310
   at MonoDevelop.Ide.Projects.NewFileDialog.OpenEvent(Object sender, EventArgs e) in
main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.Projects\NewFileDialog.cs:line 475