Revert "Fixed 'Bug 55735 - Intellisense popups are layered, intrusive, and"
This reverts commit 548c65a5d3b37bb7b11e740329bfe609c03c5117.
This is causing a stackoverflow:

Stack overflow in unmanaged: IP: 0x10127e284, fault addr: 0x7fff5b61eff8
ERROR [2017-05-25 11:38:34Z]: An unhandled exception has occured. Terminating Visual Studio? False
System.TypeInitializationException: The type initializer for '<>c' threw an exception. ---> System.OutOfMemoryException: Out of memory
  at (wrapper alloc) System.Object:AllocSmall (intptr,intptr)
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c..cctor () [0x00000] in <400071ddcfe64ed8a3531490bb763536>:0
   --- End of inner exception stack trace ---
  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.SetException (System.Exception exception) [0x0002f] in /private/tmp/source-mono-2017-04/bockbuild-2017-04/profiles/mono-mac-xamarin/build-root/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:215
  at MonoDevelop.Ide.CodeCompletion.ParameterInformationWindowManager+<PositionParameterInfoWindow>d__33.MoveNext () [0x00165] in /Users/alan/Projects/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/ParameterInformationWindowManager.cs:277
  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in /private/tmp/source-mono-2017-04/bockbuild-2017-04/profiles/mono-mac-xamarin/build-root/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:84
  at MonoDevelop.Ide.CodeCompletion.ParameterInformationWindowManager.PositionParameterInfoWindow () [0x0001f] in <5925ccd171e34f3c992af32b81e36140>:0
  at MonoDevelop.Ide.CodeCompletion.ParameterInformationWindowManager+<>c.<UpdateWindow>b__32_0 (System.Object o, System.EventArgs args) [0x00056] in /Users/alan/Projects/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/ParameterInformationWindowManager.cs:241
  at Xwt.WindowFrame.OnBoundsChanged (Xwt.BoundsChangedEventArgs a) [0x00061] in /Users/alan/Projects/monodevelop/main/external/xwt/Xwt/Xwt/WindowFrame.cs:423
  at MonoDevelop.Components.XwtPopup.OnBoundsChanged (Xwt.BoundsChangedEventArgs a) [0x00001] in /Users/alan/Projects/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Xwt/XwtPopup.cs:270
  at Xwt.WindowFrame+WindowBackendHost.OnBoundsChanged (Xwt.Rectangle bounds) [0x00001] in /Users/alan/Projects/monodevelop/main/external/xwt/Xwt/Xwt/WindowFrame.cs:91
  at Xwt.GtkBackend.WindowFrameBackend.<Move>b__27_0 () [0x00001] in /Users/alan/Projects/monodevelop/main/external/xwt/Xwt.Gtk/Xwt.GtkBackend/WindowFrameBackend.cs:142
  at Xwt.Toolkit.Invoke (System.Action a) [0x00015] in /Users/alan/Projects/monodevelop/main/external/xwt/Xwt/Xwt/Toolkit.cs:429