[Core] Fix save failed after deleting file from .NET Core project
Fixed bug #53428 - Erroneous "Save failed" popup dialogs when adding
a new file to a .NET Standard Library
https://bugzilla.xamarin.com/show_bug.cgi?id=53428

Creating a new .NET Standard Library, then removing the single
Class1.cs file from the project and then adding a new C# class
file would result in two Save failed dialogs being displayed due to
a null reference exception. The problem was that when the last file
was removed from the project the unused glob item was being removed.
This glob item was imported and would then have its parent project
set to null. This glob item was then re-used when saving the project
again a second time after the new file was added and resulted in a
null reference exception. To fix this the unused glob item is not
removed if it is imported and does not exist in the main project.

System.NullReferenceException: Object reference not set to an instance of an object
  at MonoDevelop.Projects.Project+<FindUpdateItemsForItem>c__Iterator12.MoveNext () [0x0002e] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:3386
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x0008b] in mono-x86/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:99
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00011] in mono-x86/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:861
  at MonoDevelop.Projects.Project.GenerateItemDiff (MonoDevelop.Projects.MSBuild.MSBuildItem globItem, MonoDevelop.Projects.MSBuild.MSBuildItem item, MonoDevelop.Projects.MSBuild.IMSBuildItemEvaluated evalItem) [0x0040f] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:3374
  at MonoDevelop.Projects.Project.SaveProjectItem (MonoDevelop.Core.ProgressMonitor monitor, MonoDevelop.Projects.MSBuild.MSBuildProject msproject, MonoDevelop.Projects.ProjectItem item, System.Collections.Generic.Dictionary`2[TKey,TValue] expandedItems, System.Collections.Generic.HashSet`1[T] unusedItems, System.Collections.Generic.HashSet`1[T] loadedItems, System.String pathPrefix) [0x00100] in main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:3166
  at MonoDevelop.Projects.Project.SaveProjectItems (MonoDevelop.Core.ProgressMonitor monitor, MonoDevelop.Projects.MSBuild.MSBuildProject msproject, System.Collections.Generic.HashSet`1[T] loadedItems, System.String pathPrefix) [0x00047] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:3090
  at MonoDevelop.Projects.Project.OnWriteProject (MonoDevelop.Core.ProgressMonitor monitor, MonoDevelop.Projects.MSBuild.MSBuildProject msproject) [0x00019] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:2808
  at MonoDevelop.Projects.DotNetProject.OnWriteProject (MonoDevelop.Core.ProgressMonitor monitor, MonoDevelop.Projects.MSBuild.MSBuildProject msproject) [0x00000] in monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs:1819