[PerformanceDiagnostics] Fix fatal exception when checking process
Fixed unhandled exception that terminates the IDE when checking
the watch dog process has exited. The check is made on a background
thread using a process field value that can be recreated on another
thread. This could result in the following exception:

System.InvalidOperationException: No process is associated with this object.
  at System.Diagnostics.Process.EnsureState (System.Diagnostics.Process+State state) [0x000ab]
  in mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs:1492
  at System.Diagnostics.Process.get_HasExited () [0x0000b]
  in mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs:250
  at PerformanceDiagnosticsAddIn.UIThreadMonitor.PumpErrorStream () [0x00022]
  in main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/UIThreadMonitor.cs:160

To avoid this the Process is passed to the thread start methods to
avoid the wrong Process being used.