[Core] Fix failure to open Git Status window
The Git StatusView indicates it has a file but the parent directory
of the filename is null. This was not handled by the file watcher
and resulted in the Git status window not being displayed. In the
IDE log an IndexOutOfRangeException was thrown:

Error while executing command: Review Solution and Commit
System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at MonoDevelop.Core.FilePath.IsChildPathOf (MonoDevelop.Core.FilePath basePath)
  in MonoDevelop.Core/FilePath.cs:180