Add ToArray() on the call to close open documents
ERROR [2019-09-17 20:37:16Z]: Error while reloading project wagit
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.HashSet`1+Enumerator[T].MoveNext () [0x00013] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corefx/src/System.Collections/src/System/Collections/Generic/HashSet.cs:1810
  at MonoDevelop.Ide.TypeSystem.MonoDevelopWorkspace+<>c__DisplayClass121_0.<OnProjectModified>b__1 (System.Threading.Tasks.Task`1[TResult] t) [0x000ae] in /Users/therzok/Work/md/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs:1512

This is a regression introduced by https://github.com/mono/monodevelop/pull/8639