[Mac] Fix random crash that could happen on assembly load
Assembly Load events can happen in parallel, so we need to guard it,
because Runtime.RegisterAssembly is not thread-safe

ERROR [2018-04-11 12:54:05Z]: Error while trying to load the project /Users/davidkarlas/Downloads/MVVMSample1/MVVMSample1.Core/MVVMSample1.Core.csproj
System.ArgumentException: An item with the same key has already been added. Key: FSharpBinding, Version=0.0.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000ad] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:424
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:232
  at Registrar.Registrar.RegisterAssembly (System.Reflection.Assembly assembly) [0x0004e] in /Library/Frameworks/Xamarin.Mac.framework/Versions/4.4.0.49/src/Xamarin.Mac/ObjCRuntime/Registrar.cs:2362
  at ObjCRuntime.Runtime.RegisterAssembly (System.Reflection.Assembly a) [0x0019a] in /Library/Frameworks/Xamarin.Mac.framework/Versions/4.4.0.49/src/Xamarin.Mac/ObjCRuntime/Runtime.cs:600
  at MonoDevelop.MacIntegration.MacPlatformService+<>c.<LoadNativeToolkit>b__25_0 (System.Object o, System.AssemblyLoadEventArgs args) [0x00001] in /Users/davidkarlas/GIT/MD1/monodevelop/main/src/addins/MacPlatform/MacPlatform.cs:245
  at (wrapper delegate-invoke) <Module>.invoke_void_object_AssemblyLoadEventArgs(object,System.AssemblyLoadEventArgs)
  at System.AppDomain.DoAssemblyLoad (System.Reflection.Assembly assembly) [0x00009] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System/AppDomain.cs:1285
  at (wrapper managed-to-native) System.Reflection.Assembly.LoadFrom(string,bool)
  at System.Reflection.Assembly.LoadFrom (System.String assemblyFile) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Reflection/Assembly.cs:536
  at Mono.Addins.RuntimeAddin.LoadModule (Mono.Addins.Description.ModuleDescription module, System.Collections.ArrayList asmList) [0x000a0] in /Users/davidkarlas/GIT/MD1/monodevelop/main/external/mono-addins/Mono.Addins/Mono.Addins/RuntimeAddin.cs:679
  at Mono.Addins.RuntimeAddin.EnsureAssembliesLoaded () [0x00024] in /Users/davidkarlas/GIT/MD1/monodevelop/main/external/mono-addins/Mono.Addins/Mono.Addins/RuntimeAddin.cs:718
  at Mono.Addins.RuntimeAddin.GetType (System.String typeName, System.Boolean throwIfNotFound) [0x00001] in /Users/davidkarlas/GIT/MD1/monodevelop/main/external/mono-addins/Mono.Addins/Mono.Addins/RuntimeAddin.cs:319
  at Mono.Addins.TypeExtensionNode.get_Type () [0x0002f] in /Users/davidkarlas/GIT/MD1/monodevelop/main/external/mono-addins/Mono.Addins/Mono.Addins/TypeExtensionNode.cs:104
  at Mono.Addins.TypeExtensionNode.CreateInstance () [0x00001] in /Users/davidkarlas/GIT/MD1/monodevelop/main/external/mono-addins/Mono.Addins/Mono.Addins/TypeExtensionNode.cs:93
  at Mono.Addins.InstanceExtensionNode.CreateInstance (System.Type expectedType) [0x00001] in /Users/davidkarlas/GIT/MD1/monodevelop/main/external/mono-addins/Mono.Addins/Mono.Addins/InstanceExtensionNode.cs:88
  at MonoDevelop.Projects.Extensions.SolutionItemExtensionNode.CreateExtension () [0x00001] in /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Extensions/SolutionItemExtensionNode.cs:114
  at MonoDevelop.Projects.WorkspaceObject.InitializeExtensionChain () [0x00094] in /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs:380
  at MonoDevelop.Projects.WorkspaceObject.EnsureInitialized () [0x00029] in /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs:73
  at MonoDevelop.Projects.MSBuild.MSBuildProjectService+<LoadItem>d__58.MoveNext () [0x001c9] in /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs:405
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357
  at MonoDevelop.Projects.ProjectService+<>c__DisplayClass25_0+<<ReadSolutionItem>b__0>d.MoveNext () [0x0017f] in /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectService.cs:126
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357
  at MonoDevelop.Core.Runtime+<>c__41`1+<<RunInMainThread>b__41_0>d[T].MoveNext () [0x00059] in /Users/davidkarlas/GIT/MD1/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs:386