[Packaging] .NET Standard projects can now be packaged
Fixed bug #56706 - Can not create a nuget package with Standard net
libraries
https://bugzilla.xamarin.com/show_bug.cgi?id=56706

A NuGet packaging project that referenced a .NET Standard project
that used an Sdk style project would fail to build the NuGet package.
The build would fail with an error:

Error: Project targets '.NETStandard,Version=v1.4'. It cannot be
referenced by a project that targets 'NuGet,Version=v1.0'

Updating to the latest stable NuGet.Build.Packaging 0.1.276 NuGet
package fixes the problem.

See also https://github.com/NuGet/Home/issues/4858