[Ide] Do not load locale sets on startup
On startup the LocationService was initialized so it reads the
/MonoDevelop/Ide/LocaleSet extension points to find the locales.
Now the locales are loaded when they are first requested which is
when they are used in the Preferences dialog to show the list
of available languages in the Visual Style page.

This also fixes a null reference exception since the translation
catalog was accessed by the LocaleSetLimiter in md-addins before
any addin initialized the custom translation catalog.

Failed to localize string:
System.NullReferenceException: Object reference not set to an
instance of an object
  at Xamarin.Components.Ide.TranslationCatalog.GetStringInternal (System.String phrase) [0x00002]
in Xamarin.Ide/Xamarin.Components.Ide/TranslationCatalog.cs:21

Fixes VSTS #641263 - LocationService loads addins on startup