[Core] Fix opening assembly as solution.
Fixed bug #35381 -  Error opening assembly as solution
https://bugzilla.xamarin.com/show_bug.cgi?id=35381

Previously this would fail with the exception:

Load operation failed.
System.NotSupportedException: Specified method is not supported.
  at MonoDevelop.Projects.WorkspaceObjectReader.LoadWorkspaceItem
(MonoDevelop.Core.ProgressMonitor monitor, System.String fileName)  in
core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObjectReader.cs:49

This was because the CompiledAssemblyExtension class was returning
true from CanRead when ProjectService.IsWorkspaceItemFile was
called so the wrapper solution was not being created. On master the
CanRead method returns false and would only return true when
ProjectService.IsSolutionItemFile was called.